-- PostgreSQL Schema for BTS Flip Thru

-- Generated by better-auth
create table IF NOT EXISTS "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null, "role" integer not null);

create table IF NOT EXISTS "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

create table IF NOT EXISTS "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table IF NOT EXISTS "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create index IF NOT EXISTS "session_userId_idx" on "session" ("userId");

create index IF NOT EXISTS "account_userId_idx" on "account" ("userId");

create index IF NOT EXISTS "verification_identifier_idx" on "verification" ("identifier");

-- Collections table
CREATE TABLE IF NOT EXISTS collections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    release_date DATE NOT NULL,
    collection_types INTEGER[] NOT NULL,
    version TEXT,
    version_order INTEGER
);

-- Card Sizes table
CREATE TABLE IF NOT EXISTS card_sizes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL
);

-- Photocards table
-- MEMBER MAPPING:
-- 1: RM, 2: Jin, 3: Suga, 4: J-Hope, 5: Jimin, 6: V, 7: Jung Kook
CREATE TABLE IF NOT EXISTS photocards (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id INTEGER NOT NULL,
    image_id TEXT,
    back_image_id TEXT,
    back_image_type INTEGER NOT NULL DEFAULT 0,
    card_type INTEGER NOT NULL,
    size_id INTEGER NOT NULL,
    mod_temporary BOOLEAN NOT NULL DEFAULT FALSE,
    admin_temporary BOOLEAN NOT NULL DEFAULT FALSE,
    exclusive_country INTEGER NOT NULL,
    effects INTEGER NOT NULL DEFAULT 0,
    
    -- Replaces individual member booleans
    members INTEGER[] NOT NULL,  -- Stores IDs [1, 2, 4, etc.]

    image_contributor_id TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Collection Types table
CREATE TABLE IF NOT EXISTS collection_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- Card Types table
CREATE TABLE IF NOT EXISTS card_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

-- Reports table
CREATE TABLE IF NOT EXISTS reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image_id TEXT,
    user_id TEXT,
    user_email TEXT,
    url TEXT NOT NULL,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- User Data table
CREATE TABLE IF NOT EXISTS user_data (
    user_id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    description TEXT,
    army_since DATE,
    bcd_id TEXT,
    bluesky_id TEXT,
    twitter_id TEXT,
    instagram_id TEXT,
    discord_id TEXT,
    image_id TEXT,
    profile_photocard_id INTEGER,
    bias INTEGER,
    disable_cursor BOOLEAN NOT NULL DEFAULT FALSE,
    disable_effects BOOLEAN NOT NULL DEFAULT FALSE,
    spotify_playlist TEXT,
    friends TEXT[] NOT NULL DEFAULT '{}',
    binders TEXT[] NOT NULL DEFAULT '{}',
    contributions INTEGER NOT NULL DEFAULT 0,
    saved_photocards_count INTEGER NOT NULL DEFAULT 0,
    wishlist_count INTEGER NOT NULL DEFAULT 0,
    saved_creations_count INTEGER NOT NULL DEFAULT 0
);

-- Creations table
CREATE TABLE IF NOT EXISTS creations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contributor_id TEXT NOT NULL,
    image_id TEXT NOT NULL,
    name TEXT NOT NULL,
    type INTEGER NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    collection_id INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (contributor_id) REFERENCES user_data(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_photocards (
    user_id TEXT NOT NULL,
    photocard_id INTEGER NOT NULL,
    saved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, photocard_id),
    FOREIGN KEY (user_id) REFERENCES user_data(user_id) ON DELETE CASCADE,
    FOREIGN KEY (photocard_id) REFERENCES photocards(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_wishlists (
    user_id TEXT NOT NULL,
    photocard_id INTEGER NOT NULL,
    saved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, photocard_id),
    FOREIGN KEY (user_id) REFERENCES user_data(user_id) ON DELETE CASCADE,
    FOREIGN KEY (photocard_id) REFERENCES photocards(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_saved_creations (
    user_id TEXT NOT NULL,
    creation_id INTEGER NOT NULL,
    saved_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, creation_id),
    FOREIGN KEY (user_id) REFERENCES user_data(user_id) ON DELETE CASCADE,
    FOREIGN KEY (creation_id) REFERENCES creations(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_binders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    cover_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    binder_pages INTEGER[],
    FOREIGN KEY (user_id) REFERENCES user_data(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS binder_pages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    binder_id INTEGER NOT NULL,
    page_type INTEGER NOT NULL,
    creation_ids INTEGER[] NOT NULL DEFAULT '{}',
    creation_show_front BOOLEAN[] NOT NULL DEFAULT '{}',
    creation_rotations INTEGER[] NOT NULL DEFAULT '{}',
    creation_x_positions INTEGER[] NOT NULL DEFAULT '{}',
    creation_y_positions INTEGER[] NOT NULL DEFAULT '{}',
    creation_z_indices INTEGER[] NOT NULL DEFAULT '{}',
    photocard_ids INTEGER[] NOT NULL DEFAULT '{}',
    photocard_show_front BOOLEAN[] NOT NULL DEFAULT '{}',
    photocard_rotations INTEGER[] NOT NULL DEFAULT '{}',
    photocard_x_positions INTEGER[] NOT NULL DEFAULT '{}',
    photocard_y_positions INTEGER[] NOT NULL DEFAULT '{}',
    photocard_z_indices INTEGER[] NOT NULL DEFAULT '{}',
    description TEXT,
    FOREIGN KEY (binder_id) REFERENCES user_binders(id) ON DELETE CASCADE
);

-- INDICES
CREATE INDEX IF NOT EXISTS idx_photocards_collection_id ON photocards(collection_id);
CREATE INDEX IF NOT EXISTS idx_photocards_updated_at ON photocards(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_photocards_missing_image ON photocards(id) WHERE image_id IS NULL;
CREATE INDEX IF NOT EXISTS idx_photocards_members ON photocards USING GIN (members);
CREATE INDEX IF NOT EXISTS idx_photocards_card_type ON photocards(card_type);
CREATE INDEX IF NOT EXISTS idx_photocards_size_id ON photocards(size_id);
CREATE INDEX IF NOT EXISTS idx_photocards_exclusive_country ON photocards(exclusive_country);
CREATE INDEX IF NOT EXISTS idx_photocards_image_contributor_id ON photocards(image_contributor_id);
-- Partial index for the home page "Recently Added" (only cards with images)
CREATE INDEX IF NOT EXISTS idx_photocards_recent_images ON photocards(updated_at DESC) WHERE image_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_reports_user_id ON reports(user_id);
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON reports(created_at);

CREATE INDEX IF NOT EXISTS idx_creations_contributor_id ON creations(contributor_id);
CREATE INDEX IF NOT EXISTS idx_creations_collection_id ON creations(collection_id);

CREATE INDEX IF NOT EXISTS idx_user_photocards_id ON user_photocards(user_id);
CREATE INDEX IF NOT EXISTS idx_user_photocards_saved_at ON user_photocards(saved_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_wishlists_id ON user_wishlists(user_id);
CREATE INDEX IF NOT EXISTS idx_user_wishlists_saved_at ON user_wishlists(saved_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_saved_creations_id ON user_saved_creations(user_id);
CREATE INDEX IF NOT EXISTS idx_user_saved_creations_saved_at ON user_saved_creations(saved_at DESC);

-- VIEWS
-- Using pg_class estimate for O(1) performance without triggers
CREATE OR REPLACE VIEW view_db_stats AS
SELECT
    (SELECT reltuples::INTEGER FROM pg_class WHERE relname = 'user_data') AS num_users,
    (SELECT reltuples::INTEGER FROM pg_class WHERE relname = 'photocards') AS num_photocards,
    (SELECT reltuples::INTEGER FROM pg_class WHERE relname = 'idx_photocards_missing_image') AS num_photocards_without_images,
    (SELECT reltuples::INTEGER FROM pg_class WHERE relname = 'user_binders') AS num_binders,
    (SELECT reltuples::INTEGER FROM pg_class WHERE relname = 'creations') AS num_creations;

-- MATERIALIZED VIEWS
-- Note: Whenever a new materialized view is added, make sure to add it to refresh.sql
CREATE MATERIALIZED VIEW IF NOT EXISTS view_most_contributions AS
SELECT
    image_contributor_id,
    COUNT(*) AS num_contributions
FROM photocards
GROUP BY image_contributor_id
ORDER BY num_contributions DESC
LIMIT 1;

CREATE MATERIALIZED VIEW IF NOT EXISTS view_most_owned_photocards AS
SELECT
    photocard_id,
    COUNT(*) AS num_owners
FROM user_photocards
GROUP BY photocard_id
ORDER BY num_owners DESC
LIMIT 1;

CREATE MATERIALIZED VIEW IF NOT EXISTS view_most_wishlisted_photocards AS
SELECT
    photocard_id,
    COUNT(*) AS num_wishlisted
FROM user_wishlists
GROUP BY photocard_id
ORDER BY num_wishlisted DESC
LIMIT 1;

CREATE MATERIALIZED VIEW IF NOT EXISTS view_most_saved_creations AS
SELECT
    creation_id,
    COUNT(*) AS num_saved
FROM user_saved_creations
GROUP BY creation_id
ORDER BY num_saved DESC
LIMIT 1;


-- STORED PROCEDURES

-- 1. Add Collection with Photocards
CREATE OR REPLACE PROCEDURE sp_add_collection_with_photocards(
    p_collection JSONB,
    p_photocards JSONB,
    p_user_id TEXT,
    OUT p_new_collection_id INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_pc JSONB;
    v_members INTEGER[];
    v_collection_types INTEGER[];
BEGIN
    v_collection_types := ARRAY(SELECT jsonb_array_elements_text(p_collection->'collection_types')::INTEGER);

    INSERT INTO collections (name, release_date, collection_types, version, version_order)
    VALUES (
        (p_collection->>'name')::TEXT,
        (p_collection->>'release_date')::DATE,
        v_collection_types,
        (p_collection->>'version')::TEXT,
        (p_collection->>'version_order')::INTEGER
    )
    RETURNING id INTO p_new_collection_id;

    FOR v_pc IN SELECT * FROM jsonb_array_elements(p_photocards)
    LOOP
        v_members := ARRAY(SELECT jsonb_array_elements_text(v_pc->'members')::INTEGER);

        INSERT INTO photocards (
            collection_id, image_id, back_image_id, back_image_type,
            card_type, size_id, mod_temporary, admin_temporary,
            exclusive_country, effects,
            members,
            image_contributor_id, updated_at
        )
        VALUES (
            p_new_collection_id,
            (v_pc->>'image_id')::TEXT,
            (v_pc->>'back_image_id')::TEXT,
            (v_pc->>'back_image_type')::INTEGER,
            (v_pc->>'card_type')::INTEGER,
            (v_pc->>'size_id')::INTEGER,
            (v_pc->>'mod_temporary')::BOOLEAN,
            (v_pc->>'admin_temporary')::BOOLEAN,
            (v_pc->>'exclusive_country')::INTEGER,
            (v_pc->>'effects')::INTEGER,
            v_members,
            p_user_id,
            NOW()
        );
    END LOOP;
END;
$$;

-- 2. Update Collection with Photocards
CREATE OR REPLACE PROCEDURE sp_update_collection_with_photocards(
    p_collection_id INTEGER,
    p_collection JSONB,
    p_photocards JSONB,
    p_user_id TEXT,
    p_role INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_ids INTEGER[];
    v_incoming_ids INTEGER[];
    v_pc JSONB;
    v_pc_id INTEGER;
    v_members INTEGER[];
    v_collection_types INTEGER[];
BEGIN
    v_collection_types := ARRAY(SELECT jsonb_array_elements_text(p_collection->'collection_types')::INTEGER);

    UPDATE collections
    SET name = (p_collection->>'name')::TEXT,
        release_date = (p_collection->>'release_date')::DATE,
        collection_types = v_collection_types,
        version = (p_collection->>'version')::TEXT,
        version_order = (p_collection->>'version_order')::INTEGER
    WHERE id = p_collection_id;

    SELECT ARRAY_AGG(id) INTO v_current_ids FROM photocards WHERE collection_id = p_collection_id;

    SELECT ARRAY_AGG((x->>'id')::INTEGER) INTO v_incoming_ids
    FROM jsonb_array_elements(p_photocards) x
    WHERE (x->>'id') IS NOT NULL;

    IF v_current_ids IS NOT NULL THEN
        DELETE FROM photocards
        WHERE collection_id = p_collection_id
        AND id = ANY(v_current_ids)
        AND (v_incoming_ids IS NULL OR id != ALL(v_incoming_ids))
        -- Prevention: If user is mod (1), cannot delete admin_temporary (false) cards.
        -- Admins (2) can delete everything.
        AND (admin_temporary = TRUE OR p_role = 2); 
    END IF;

    FOR v_pc IN SELECT * FROM jsonb_array_elements(p_photocards)
    LOOP
        v_pc_id := (v_pc->>'id')::INTEGER;

        v_members := ARRAY(SELECT jsonb_array_elements_text(v_pc->'members')::INTEGER);

        IF v_pc_id IS NOT NULL THEN
            UPDATE photocards SET
                image_contributor_id = CASE 
                    WHEN (image_id IS DISTINCT FROM (v_pc->>'image_id')::TEXT) 
                      OR (back_image_id IS DISTINCT FROM (v_pc->>'back_image_id')::TEXT)
                    THEN p_user_id 
                    ELSE image_contributor_id 
                END,
                image_id = (v_pc->>'image_id')::TEXT,
                back_image_id = (v_pc->>'back_image_id')::TEXT,
                back_image_type = (v_pc->>'back_image_type')::INTEGER,
                card_type = (v_pc->>'card_type')::INTEGER,
                size_id = (v_pc->>'size_id')::INTEGER,
                effects = (v_pc->>'effects')::INTEGER,
                exclusive_country = (v_pc->>'exclusive_country')::INTEGER,
                members = v_members,
                updated_at = NOW(),
                mod_temporary = (v_pc->>'mod_temporary')::BOOLEAN,
                admin_temporary = (v_pc->>'admin_temporary')::BOOLEAN
            WHERE id = v_pc_id;
        ELSE
             INSERT INTO photocards (
                collection_id, image_id, back_image_id, back_image_type,
                card_type, size_id, exclusive_country, effects,
                members,
                image_contributor_id, updated_at,
                mod_temporary, admin_temporary
            )
            VALUES (
                p_collection_id,
                (v_pc->>'image_id')::TEXT,
                (v_pc->>'back_image_id')::TEXT,
                (v_pc->>'back_image_type')::INTEGER,
                (v_pc->>'card_type')::INTEGER,
                (v_pc->>'size_id')::INTEGER,
                (v_pc->>'exclusive_country')::INTEGER,
                (v_pc->>'effects')::INTEGER,
                v_members,
                p_user_id,
                NOW(),
                (v_pc->>'mod_temporary')::BOOLEAN,
                (v_pc->>'admin_temporary')::BOOLEAN
            );
        END IF;
    END LOOP;
END;
$$;

-- 3. User Stats Triggers

CREATE OR REPLACE FUNCTION tf_update_saved_photocards_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE user_data SET saved_photocards_count = saved_photocards_count + 1 WHERE user_id = NEW.user_id;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE user_data SET saved_photocards_count = saved_photocards_count - 1 WHERE user_id = OLD.user_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_saved_photocards_count ON user_photocards;
CREATE TRIGGER trg_update_saved_photocards_count
AFTER INSERT OR DELETE ON user_photocards
FOR EACH ROW EXECUTE FUNCTION tf_update_saved_photocards_count();

CREATE OR REPLACE FUNCTION tf_update_wishlist_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE user_data SET wishlist_count = wishlist_count + 1 WHERE user_id = NEW.user_id;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE user_data SET wishlist_count = wishlist_count - 1 WHERE user_id = OLD.user_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_wishlist_count ON user_wishlists;
CREATE TRIGGER trg_update_wishlist_count
AFTER INSERT OR DELETE ON user_wishlists
FOR EACH ROW EXECUTE FUNCTION tf_update_wishlist_count();

CREATE OR REPLACE FUNCTION tf_update_saved_creations_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE user_data SET saved_creations_count = saved_creations_count + 1 WHERE user_id = NEW.user_id;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE user_data SET saved_creations_count = saved_creations_count - 1 WHERE user_id = OLD.user_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_saved_creations_count ON user_saved_creations;
CREATE TRIGGER trg_update_saved_creations_count
AFTER INSERT OR DELETE ON user_saved_creations
FOR EACH ROW EXECUTE FUNCTION tf_update_saved_creations_count();

CREATE OR REPLACE FUNCTION tf_update_contributions_count()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        UPDATE user_data SET contributions = contributions + 1 WHERE user_id = NEW.image_contributor_id;
    ELSIF (TG_OP = 'DELETE') THEN
        UPDATE user_data SET contributions = contributions - 1 WHERE user_id = OLD.image_contributor_id;
    ELSIF (TG_OP = 'UPDATE') THEN
        IF (OLD.image_contributor_id IS DISTINCT FROM NEW.image_contributor_id) THEN
            UPDATE user_data SET contributions = contributions - 1 WHERE user_id = OLD.image_contributor_id;
            UPDATE user_data SET contributions = contributions + 1 WHERE user_id = NEW.image_contributor_id;
        END IF;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_contributions_count ON photocards;
CREATE TRIGGER trg_update_contributions_count
AFTER INSERT OR UPDATE OR DELETE ON photocards
FOR EACH ROW EXECUTE FUNCTION tf_update_contributions_count();
